a:4:{s:5:"child";a:1:{s:0:"";a:1:{s:3:"rss";a:1:{i:0;a:6:{s:4:"data";s:3:"


";s:7:"attribs";a:1:{s:0:"";a:1:{s:7:"version";s:3:"2.0";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:1:{s:7:"channel";a:1:{i:0;a:6:{s:4:"data";s:28:"
	
	
	
	
	
	
	
	
	


	
	
	
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:3:{s:0:"";a:9:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"Our learning experiences……";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:30:"https://nikasemo.wordpress.com";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:8:"Nikasemo";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:13:"lastBuildDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Tue, 15 Mar 2016 20:56:19 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"language";a:1:{i:0;a:5:{s:4:"data";s:2:"en";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:9:"generator";a:1:{i:0;a:5:{s:4:"data";s:21:"http://wordpress.com/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:5:"cloud";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:5:{s:6:"domain";s:22:"nikasemo.wordpress.com";s:4:"port";s:2:"80";s:4:"path";s:17:"/?rsscloud=notify";s:17:"registerProcedure";s:0:"";s:8:"protocol";s:9:"http-post";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:5:"image";a:1:{i:0;a:6:{s:4:"data";s:11:"
		
		
		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:3:{s:3:"url";a:1:{i:0;a:5:{s:4:"data";s:35:"https://s2.wp.com/i/buttonw-com.png";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"Our learning experiences……";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:30:"https://nikasemo.wordpress.com";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}s:4:"item";a:1:{i:0;a:6:{s:4:"data";s:122:"
		
		
		
		
		
				

		
		
				
			
		
	
		

		

		

		

		

		

		

		

		

		

		

		

		

		

		

		

		

		

		

		
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:6:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"Who we are: Beliefs and values";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:72:"https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:80:"https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/#respond";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Wed, 09 Mar 2016 18:58:32 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:1:{i:0;a:5:{s:4:"data";s:13:"Uncategorized";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:34:"http://nikasemo.wordpress.com/?p=5";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:538:"We open-mindedly started our second inquiry of the academic year- “Who we are”. We set out to explore the central idea: “Systems that define beliefs and values offer explanations about the world around us and what it means to be human”, specifically setting our focus on: • Similarities and differences between belief systems (secular and [&#8230;]<img alt="" border="0" src="https://pixel.wp.com/b.gif?host=nikasemo.wordpress.com&#038;blog=100728295&#038;post=5&#038;subd=nikasemo&#038;ref=&#038;feed=1" width="1" height="1" />";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:6:"nortey";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:33000:"<p>We open-mindedly started our second inquiry of the academic year- “Who we are”. We set out to explore the central idea: “Systems that define beliefs and values offer explanations about the world around us and what it means to be human”, specifically setting our focus on:</p>
<p>• Similarities and differences between belief systems (secular and faith-based).<br />
• How beliefs and values contribute to the formation and actions of communities.<br />
• The impact of spiritual traditions on societies.</p>
<p>We started our unit by making the learners write what they ‘believed in’ also known as “I believe statement” as a Tuning in learning engagement. It was an interesting learning engagement for Teachers and pupils alike. Most of the learners were excited to share their faith and what they believed in. A cocktail of Muslims, Christians and an atheist was a great way of starting a sensitive, fun and learning filled 5 weeks unit of inquiry lessons. Also, we provoked the minds of the learners with the following scenario:<br />
“Imagine you are on an island with all your basic needs: food, shelter, clothing etc. what 5 other things would you like to take with you?” and “their daily routines”<br />
Our learners were able to list a few things but the one thing that ran through their work was the need to take a prayer mat, Bible or Quran, phone/iPad, cars etc. As part of putting up our theme board, we printed common symbols of the world’s top 11 religions. We observed that most of our learners had knowledge of just a few of such symbols so we encouraged them to find out more about other symbols and the religions they represented.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0607.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="&quot;I believe statements&quot;" data-attachment-id="10" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0607.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361726272&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;200&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0607.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0607.jpg?w=750" /></a>

<p>As part of our investigation, we asked them a couple of questions—“Do you believe in God?” and “Do you think religion is important?”<br />
The curiosity of our learners set them on a journey around the school to conduct a survey as well as collect data about the number people who belonged to the top 11 world religions. Our learners were taken aback when a teacher mentioned that she is agnostic.</p>
<div data-shortcode="caption" id="attachment_16" style="width: 3466px" class="wp-caption alignnone"><img class="alignnone size-full wp-image-16" src="https://nikasemo.files.wordpress.com/2016/03/sam_0610.jpg?w=750" alt="SAMSUNG CAMERA PICTURES"   /><p class="wp-caption-text">Survey about different religions in ARIS.</p></div>
<p>We were privileged to have four guest speakers; Madam Majida, Mr Emmanuel and Madam Simran in our school to talk to us about their faiths; Islam, Christianity and Sikhism respectively. Also, there was a presentation by a parent, an atheist, about why she does not believe in God. This created room for more questions than answers because most of the learners had lots of questions brewing in their heads. Most of us did have fair knowledge of both Christianity and Islam so much of the stuff that was presented to us wasn’t new. We did, however, pick up a new thing or two about these religions but the presentation on Sikhism by Madam Simran was particularly insightful and interesting as well. Even though the presentation was a short one, it provided vital information for pupils and teachers alike. She made mention of “the ten Gurus”, with particular reference to Guru Gobind Singh in Sikhism and continued to talk about some practices, place of worship and shared a number of Sikh beliefs.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-4/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0436.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="Guest speaker on Islam." data-attachment-id="22" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0436.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361378199&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0436.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0436.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-5/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0505.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="Guest speaker on Christianity." data-attachment-id="23" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0505.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;4.4&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361627350&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;9.6&quot;,&quot;iso&quot;:&quot;480&quot;,&quot;shutter_speed&quot;:&quot;0.033333333333333&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0505.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0505.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-6/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0536.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="Guest speaker on Sikhism." data-attachment-id="24" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0536.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.5&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361719197&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;5.8&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.066666666666667&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0536.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0536.jpg?w=750" /></a>

<p>Also, we made stops at the Holy Trinity Cathedral in Adabraka, a Mosque at Dzorwulu, and a Gurudwara at Tudu in Accra.<br />
On arrival at the Holy Trinity Cathedral, our learners beamed with smiles as they disembarked the bus to be taken round the Holy Trinity Cathedral premises. We walked into the main church auditorium as quietly as we possibly could as they were minutes away from starting a mid-week service. That presented an opportunity for the children to know how Roman Catholics, a denomination of Christians, worship. A few of the Roman Catholic routines triggered lots of questions from the learners. Our tour guide explained a number of Christian beliefs and took time to answer the learners’ questions as well. Several lit candles adorned the statue of Jesus and Mary. Participants of the service knelt down to worship their deity. Others lowered their lit candle and eventually pitched it on a virtually exhausted concrete mantelpiece. The learners continued asking meaningful questions and paid close attention to every snippet of information fed them.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-7/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0699.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="Trip to the church" data-attachment-id="27" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0699.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;5.8&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361797669&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;24.1&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.25&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0699.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0699.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-8/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0716.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="Trip to the church" data-attachment-id="28" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0716.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361798204&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.1&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0716.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0716.jpg?w=750" /></a>

<p>After about an hour and a half at the church premises, we left for the Sikh temple, Gurudwara. There was particularly heavy vehicular traffic on the road to Accra central, which was where the Gurudwara was located. The learners were very much excited to see the hustle and bustle of the central business district. Several hawkers on the street frequently waved at the pupils (I suspect this was due to the skin colour of the pupils – they were undoubtedly presumed to be foreigners) at times when our vehicle was caught in traffic. By and large, Ghanaians are a very warm, welcoming and hospitable people and this courtesy is particularly extended to people believed to be from outside this country.<br />
Finally, we arrived at the Gurudwara. The learners anxiously climbed upstairs to be shown around because for most of us that represented a first visit to a Sikh temple. As an omen of acknowledgement of the sanctity of the temple, we took off our shoes as was required of us before making entry through a narrow but nicely decorated door that led to the temple. An elderly man in a long white robe and with an amazingly long white beard was patiently waiting at the main entrance of the temple to assist us learn how to tie a turban. Some smooth pleasant music greeted us on our way in. We entered the temple quietly to see three men passionately playing three different instruments while singing. We sat on a red and yellow themed woolen floor carpet with our legs crossed. The songs these men sang were quite similar to hymns sung at Church or Quran recitals at the Mosque. The priest led us through a short prayer after which a special meal was served.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-9/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0735.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="At the Sikh temple,Gurudwara." data-attachment-id="36" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0735.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361802285&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.125&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0735.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0735.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-10/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0740.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="At the Sikh temple,Gurudwara." data-attachment-id="37" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0740.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1361802372&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.1&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0740.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0740.jpg?w=750" /></a>

<p>Soon, it was time for questions and the learners took turns, seated in a semi-circular fashion, to ask questions they had prepared and on any other matter that boggled their minds. The priests were patient enough to discuss quite a number of Sikh beliefs and at the same time highlighted some physical characteristics of Sikhs. All too soon, it was time to leave already. We had one more place to visit and with the traffic situation in Accra, it would have represented poor time management on our part had we stayed any longer.</p>
<p>Much to our surprise, in much less time than we had anticipated, we arrived at a huge and beautiful dome-shaped edifice, the mosque located south of Dzorwulu.Most of our learners were impatiently waiting to get off the bus to say the afternoon prayers. Unfortunately, the Imam had taken a time out. Madam Majida, a RE teacher, and a Muslim herself, took the trouble of taking us through the process of offering a prayer and some of the learners who had never had this experience seized the opportunity to perform a prayer. I must say that most of the learners walked on air after the exercise possibly because it was their first experience.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/20151111_134327/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/20151111_134327.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="A trip to the moque." data-attachment-id="45" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/20151111_134327.jpg" data-orig-size="2592,1944" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;2.2&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;SM-P555&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1447249407&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;3.31&quot;,&quot;iso&quot;:&quot;80&quot;,&quot;shutter_speed&quot;:&quot;0.03030303030303&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="20151111_134327" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/20151111_134327.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/20151111_134327.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/20151111_135150/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/20151111_135150.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="A trip to the moque." data-attachment-id="46" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/20151111_135150.jpg" data-orig-size="2592,1944" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;2.2&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;SM-P555&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;1447249910&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;3.31&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.071428571428571&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="20151111_135150" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/20151111_135150.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/20151111_135150.jpg?w=750" /></a>

<p>The ‘Going Further’ stage was undoubtedly the ‘aha moment’ of the unit. The movie, PK by Amir Khan, perfectly suited the unit. PK as summarized by Jagdish Keshav&#8211;<br />
<em>“PK the alien being, a gentle one who encounters the other side of God and religion on earth, in India. He comes across as a simpleton, an innocent being who represents his kind from a distant planet. He meets Jaggu, Anushka Sharma, and the plot unravels soon of how the contemporary society has been taken over dogmatic preachers from all major religions. Of how the universal message of God is forgotten and of how people are manipulated by the so-called religious leaders, aptly called as Managers by PK. The movie is symbolic of how convoluted our belief system is, be it Hinduism, Islam or Christianity”- Jagdish Keshav</em><br />
The learners really enjoyed the movie and most importantly it highlighted the necessary elements that hinged on the tenets of the unit of inquiry. It is my hope that the producers and IB would strike an agreement so the movies can be used as an authorized unit resource.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-11/#main'><img width="150" height="113" src="https://nikasemo.files.wordpress.com/2016/03/sam_0791.jpg?w=150&#038;h=113" class="attachment-thumbnail size-thumbnail" alt="The movie, PK." data-attachment-id="51" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0791.jpg" data-orig-size="4608,3456" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;4.9&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1362325525&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;13.2&quot;,&quot;iso&quot;:&quot;320&quot;,&quot;shutter_speed&quot;:&quot;0.033333333333333&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0791.jpg?w=300" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0791.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-12/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_0797.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="The movie, PK." data-attachment-id="52" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0797.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.9&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1362339996&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;7.6&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0797.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0797.jpg?w=750" /></a>

<p>&nbsp;</p>
<p>Furthermore, we learned about some people who have contributed immensely to world peace despite their different religions; Nelson Mandela, Mahatma Gandhi and Abraham Lincoln, Muhammad Ali among others. These legends made massive contributions from politics to slave abolition and racial equality. Also, we compared the popular story of “the Prodigal son” by Gautama Buddha and Jesus Christ- a parable whose different accounts by the aforementioned men shared a number of similarities and at the same time had some differences. We integrated our English lesson by making each learner write a poem on religion.</p>
<p>The next stage was the ‘Making Connection stage’. It was another fascinating stage of the unit; we learned about some Ghanaian beliefs. I must confess that I personally found some of the beliefs to be ridiculous and incredible, for instance, it is popularly believed that ‘if one whistles at night one would see a ghost’. Another equally ridiculous one has it that “having itchy palm means one would become wealthy”. Another interesting one claims that if one sings while taking their bath, it would lead to the death of one’s mother. In addition, the learners randomly chose two religions and compared and contrasted them which in a way served as a formative assessment.</p>
<p>Finally, it was time for reflection and taking action stage. The learners adopted beliefs from another religion apart from theirs that stood out for them and eventually created their own set of beliefs as well as writing poems about the various faiths. The learners cooperated well in most of the learning engagements and they really showed a high sense of respect for each other’s faith. I must confess that for the first time in my life I observed learners particularly at this age who share different faiths harmoniously respected one’s belief in all the activities we carried out.</p>

<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-18/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_1094.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="SAMSUNG CAMERA PICTURES" data-attachment-id="63" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_1094.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1364146576&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;200&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_1094.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_1094.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-17/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_1089.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="SAMSUNG CAMERA PICTURES" data-attachment-id="62" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_1089.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1364146511&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;320&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_1089.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_1089.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-16/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_1087.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="Poem on religion." data-attachment-id="61" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_1087.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1364146491&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;400&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_1087.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_1087.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-15/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_1085.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="Poem on religion." data-attachment-id="60" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_1085.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.7&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1364146472&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;6.7&quot;,&quot;iso&quot;:&quot;320&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_1085.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_1085.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-14/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_1084.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="Poem on religion." data-attachment-id="59" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_1084.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.7&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1364146465&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;6.7&quot;,&quot;iso&quot;:&quot;320&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_1084.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_1084.jpg?w=750" /></a>
<a href='https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/samsung-camera-pictures-13/#main'><img width="113" height="150" src="https://nikasemo.files.wordpress.com/2016/03/sam_0794.jpg?w=113&#038;h=150" class="attachment-thumbnail size-thumbnail" alt="SAMSUNG CAMERA PICTURES" data-attachment-id="58" data-orig-file="https://nikasemo.files.wordpress.com/2016/03/sam_0794.jpg" data-orig-size="3456,4608" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;3.1&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;WB30F\/WB31F\/WB32F&quot;,&quot;caption&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;created_timestamp&quot;:&quot;1362339961&quot;,&quot;copyright&quot;:&quot;Copyright 2012&quot;,&quot;focal_length&quot;:&quot;4.3&quot;,&quot;iso&quot;:&quot;100&quot;,&quot;shutter_speed&quot;:&quot;0.05&quot;,&quot;title&quot;:&quot;SAMSUNG CAMERA PICTURES&quot;,&quot;orientation&quot;:&quot;1&quot;,&quot;keywords&quot;:&quot;Array&quot;}" data-image-title="SAMSUNG CAMERA PICTURES" data-image-description="" data-medium-file="https://nikasemo.files.wordpress.com/2016/03/sam_0794.jpg?w=225" data-large-file="https://nikasemo.files.wordpress.com/2016/03/sam_0794.jpg?w=750" /></a>

<p>&nbsp;</p>
<p>&nbsp;</p><br />  <a rel="nofollow" href="http://feeds.wordpress.com/1.0/gocomments/nikasemo.wordpress.com/5/"><img alt="" border="0" src="http://feeds.wordpress.com/1.0/comments/nikasemo.wordpress.com/5/" /></a> <img alt="" border="0" src="https://pixel.wp.com/b.gif?host=nikasemo.wordpress.com&#038;blog=100728295&#038;post=5&#038;subd=nikasemo&#038;ref=&#038;feed=1" width="1" height="1" />";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:77:"https://nikasemo.wordpress.com/2016/03/09/who-we-are-beliefs-and-values/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"0";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:29:"http://search.yahoo.com/mrss/";a:1:{s:7:"content";a:20:{i:0;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:83:"https://2.gravatar.com/avatar/52f60a7b8349f636edeeefa541b1ca64?s=96&d=identicon&r=G";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:12:"nazeernortey";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:1;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0607.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:22:""I believe statements"";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:2;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:57:"https://nikasemo.files.wordpress.com/2016/03/sam_0610.jpg";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:23:"SAMSUNG CAMERA PICTURES";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:3;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0436.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:23:"Guest speaker on Islam.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:4;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0505.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"Guest speaker on Christianity.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:5;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0536.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:25:"Guest speaker on Sikhism.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:6;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0699.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:18:"Trip to the church";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:7;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0716.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:18:"Trip to the church";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:8;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0735.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:29:"At the Sikh temple,Gurudwara.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:9;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0740.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:29:"At the Sikh temple,Gurudwara.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:10;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:70:"https://nikasemo.files.wordpress.com/2016/03/20151111_134327.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:20:"A trip to the moque.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:11;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:70:"https://nikasemo.files.wordpress.com/2016/03/20151111_135150.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:20:"A trip to the moque.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:12;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0791.jpg?w=150";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:14:"The movie, PK.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:13;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0797.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:14:"The movie, PK.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:14;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_1094.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:23:"SAMSUNG CAMERA PICTURES";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:15;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_1089.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:23:"SAMSUNG CAMERA PICTURES";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:16;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_1087.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:17:"Poem on religion.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:17;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_1085.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:17:"Poem on religion.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:18;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_1084.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:17:"Poem on religion.";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:19;a:6:{s:4:"data";s:7:"
			
		";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"url";s:63:"https://nikasemo.files.wordpress.com/2016/03/sam_0794.jpg?w=113";s:6:"medium";s:5:"image";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:29:"http://search.yahoo.com/mrss/";a:1:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:23:"SAMSUNG CAMERA PICTURES";s:7:"attribs";a:1:{s:0:"";a:1:{s:4:"type";s:4:"html";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}}}}}s:27:"http://www.w3.org/2005/Atom";a:1:{s:4:"link";a:3:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:4:"href";s:36:"https://nikasemo.wordpress.com/feed/";s:3:"rel";s:4:"self";s:4:"type";s:19:"application/rss+xml";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:1;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:4:{s:3:"rel";s:6:"search";s:4:"type";s:37:"application/opensearchdescription+xml";s:4:"href";s:38:"https://nikasemo.wordpress.com/osd.xml";s:5:"title";s:30:"Our learning experiences......";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}i:2;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:2:{s:3:"rel";s:3:"hub";s:4:"href";s:45:"https://nikasemo.wordpress.com/?pushpress=hub";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:44:"http://purl.org/rss/1.0/modules/syndication/";a:2:{s:12:"updatePeriod";a:1:{i:0;a:5:{s:4:"data";s:6:"hourly";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:15:"updateFrequency";a:1:{i:0;a:5:{s:4:"data";s:1:"1";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}}}}}}s:4:"type";i:128;s:7:"headers";a:9:{s:6:"server";s:5:"nginx";s:4:"date";s:29:"Tue, 15 Mar 2016 20:56:19 GMT";s:12:"content-type";s:34:"application/rss+xml; charset=UTF-8";s:10:"connection";s:10:"keep-alive";s:8:"x-hacker";s:108:"If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.";s:13:"last-modified";s:29:"Tue, 15 Mar 2016 20:56:19 GMT";s:4:"x-nc";s:11:"MISS dca 30";s:4:"x-ac";s:10:"1.fra _dca";s:25:"strict-transport-security";s:16:"max-age=15552000";}s:5:"build";s:14:"20121030175403";}