a:4:{s:5:"child";a:1:{s:0:"";a:1:{s:3:"rss";a:1:{i:0;a:6:{s:4:"data";s:3:"


";s:7:"attribs";a:1:{s:0:"";a:1:{s:7:"version";s:3:"2.0";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:1:{s:7:"channel";a:1:{i:0;a:6:{s:4:"data";s:22:"
	
	
	
	
	
	
	
	
	
	
	";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:3:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:17:"ARIS Parents Blog";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:31:"https://parentsblog.aris.edu.gh";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:45:"A writing space for ARIS mommies and daddies ";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:13:"lastBuildDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Sat, 12 Nov 2016 12:56:50 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"language";a:1:{i:0;a:5:{s:4:"data";s:5:"en-US";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:9:"generator";a:1:{i:0;a:5:{s:4:"data";s:30:"https://wordpress.org/?v=4.6.1";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"item";a:1:{i:0;a:6:{s:4:"data";s:42:"
		
		
		
		
		
				

		
		
				
			
		
		";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:5:{s:0:"";a:7:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:63:"Why this Father is Excited to Join the ARIS Book Worm Challenge";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:95:"https://parentsblog.aris.edu.gh/2016/11/11/this-father-is-excited-to-join-bookworm-competition/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:104:"https://parentsblog.aris.edu.gh/2016/11/11/this-father-is-excited-to-join-bookworm-competition/#comments";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 11 Nov 2016 18:24:29 +0000";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"category";a:1:{i:0;a:5:{s:4:"data";s:13:"Uncategorized";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:36:"https://parentsblog.aris.edu.gh/?p=1";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:568:"As a passionate reader, I was very happy to learn about ARIS&#8217; Book worm challenge, which invites members of the ARIS community to read as many books as possible throughout the month of November. It was an opportunity for me to take part in a common educational experience with my family, and a chance to &#8230; <a href="https://parentsblog.aris.edu.gh/2016/11/11/this-father-is-excited-to-join-bookworm-competition/" class="more-link">Continue reading<span class="screen-reader-text"> "Why this Father is Excited to Join the ARIS Book Worm Challenge"</span></a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:15:"Mustapha Hamoui";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:40:"http://purl.org/rss/1.0/modules/content/";a:1:{s:7:"encoded";a:1:{i:0;a:5:{s:4:"data";s:6040:"<p>As a passionate reader, I was very happy to learn about ARIS&#8217; Book worm challenge, which invites members of the ARIS community to read as many books as possible throughout the month of November. It was an opportunity for me to take part in a common educational experience with my family, and a chance to help my children love reading the way I do.</p>
<h3>What we are planning to read</h3>
<p>Our entire family is taking part of this event. Here are the books we&#8217;re reading:</p>
<h4>Malek, Age 7, Year 3</h4>
<p>Malek is a big fan of Star Wars and Marvel Comics. The <a href="https://aris.edu.gh/about-us/facilities/library-multimedia-center" target="_blank">ARIS library</a> has been providing him with all the books his heart desires. I love watching him lying in his bed, so engrossed in reading that he doesn&#8217;t even notice me when I come in the room:</p>
<p><img class="alignnone size-large wp-image-11" src="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2580-1024x690.jpg" alt="Marvel Comics and Star Wars Books" width="840" height="566" srcset="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2580-1024x690.jpg 1024w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2580-300x202.jpg 300w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2580-768x517.jpg 768w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2580-1200x808.jpg 1200w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px" /></p>
<h4>Samah, Age 3, Nursery</h4>
<p>My little girl is still too young to read, but that doesn&#8217;t mean she can&#8217;t be a book worm! She loves books as physical objects and she always asks us to read for her. This is the one she&#8217;s addicted to these days:</p>
<p><img class="alignnone size-large wp-image-12" src="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2581-1024x768.jpg" alt="Farmyard Friends Book" width="840" height="630" srcset="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2581-1024x768.jpg 1024w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2581-300x225.jpg 300w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2581-768x576.jpg 768w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/IMG_2581-1200x900.jpg 1200w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px" /></p>
<h4>Mommy, (Age Hidden)</h4>
<p>Anyone who has young kids knows that mommies can get really really busy. But my wife is playing along! She will be reading <a href="http://gladwell.com/blink/" target="_blank">Blink, By Malcom Gladwell</a></p>
<p><img class="alignnone size-large wp-image-13" src="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/blink-1024x576.jpg" alt="Blink, by Malcom Gladwell" width="840" height="473" srcset="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/blink-1024x576.jpg 1024w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/blink-300x169.jpg 300w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/blink-768x432.jpg 768w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/blink.jpg 1150w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px" /></p>
<p>Here&#8217;s how the author describes the book:</p>
<blockquote><p>Blink is a book about how we think without thinking, about choices that seem to be made in an instant-in the blink of an eye-that actually aren’t as simple as they seem.</p></blockquote>
<p>Exciting stuff!</p>
<h4>Daddy, (Old)</h4>
<p>I&#8217;m a fan of the sci-fi/fantasy genre. I also like crime thrillers and non fiction business books. Here are the books I&#8217;m planning to read:</p>
<p><img class="alignnone size-full wp-image-16" src="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/mustapha-books.jpg" alt="Morning Star - The Girl on The Train - Zero to One" width="840" height="422" srcset="https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/mustapha-books.jpg 840w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/mustapha-books-300x151.jpg 300w, https://parentsblog.aris.edu.gh/wp-content/uploads/2016/11/mustapha-books-768x386.jpg 768w" sizes="(max-width: 709px) 85vw, (max-width: 909px) 67vw, (max-width: 1362px) 62vw, 840px" /></p>
<ol>
<li><a href="https://www.amazon.com/Morning-Star-Rising-Trilogy-Book-ebook/dp/B00SPVPX2G">Morning Star by Piece Brown</a>: This is the third book of the <a href="https://www.amazon.com/gp/product/B0159URANK/ref=series_rw_dp_sw">Red Rising Trilogy</a>. I had already read the first two books and I really enjoyed them</li>
<li><a href="https://www.amazon.com/Girl-Train-Novel-Paula-Hawkins-ebook/dp/B00L9B7IKE/ref=sr_1_1?s=digital-text&amp;ie=UTF8&amp;qid=1478939249&amp;sr=1-1" target="_blank">Girl on The Train, by Paula Hawkins</a>. This is a crime thriller that took the world by storm last year and was turned into a movie</li>
<li><a href="https://www.amazon.com/Zero-One-Notes-Startups-Future-ebook/dp/B00J6YBOFQ/ref=sr_1_1?s=digital-text&amp;ie=UTF8&amp;qid=1478939326&amp;sr=1-1&amp;keywords=zero+to+one" target="_blank">Zero to One, by Peter Thiel</a>. The author is a well known, contrarian and very successful investor in silicon valley, and was the only one to back Donald Trump for the American presidency. This is his book about how to think about starting up a new business</li>
</ol>
<p>I&#8217;m writing this on November 11 and I&#8217;m already done with <em>Morning Star</em> and on my way to finish <em>The Girl on the Train</em>. I may need to add more books to my list. I&#8217;m happy to receive recommendations!</p>
<h3>Let&#8217;s all take part of this</h3>
<p>It&#8217;s never too late to join the book worm challenge. I encourage you all to take part of it because reading with your kids is really a wonderful and rewarding experience. I am very thankful to ARIS for giving me this opportunity.</p>
<p><em>Mustapha Hamoui.<br />
ARIS Daddy</em></p>
";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:36:"http://wellformedweb.org/CommentAPI/";a:1:{s:10:"commentRss";a:1:{i:0;a:5:{s:4:"data";s:100:"https://parentsblog.aris.edu.gh/2016/11/11/this-father-is-excited-to-join-bookworm-competition/feed/";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:38:"http://purl.org/rss/1.0/modules/slash/";a:1:{s:8:"comments";a:1:{i:0;a:5:{s:4:"data";s:1:"2";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}s:27:"http://www.w3.org/2005/Atom";a:1:{s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:4:"href";s:37:"https://parentsblog.aris.edu.gh/feed/";s:3:"rel";s:4:"self";s:4:"type";s:19:"application/rss+xml";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:44:"http://purl.org/rss/1.0/modules/syndication/";a:2:{s:12:"updatePeriod";a:1:{i:0;a:5:{s:4:"data";s:6:"hourly";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:15:"updateFrequency";a:1:{i:0;a:5:{s:4:"data";s:1:"1";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}}}}}}s:4:"type";i:128;s:7:"headers";a:9:{s:4:"date";s:29:"Tue, 13 Jun 2017 06:04:26 GMT";s:6:"server";s:22:"Apache/2.4.10 (Ubuntu)";s:13:"last-modified";s:29:"Sat, 12 Nov 2016 12:56:50 GMT";s:4:"etag";s:39:""4e185bc15828f86d9d9bb2cb62df7c4e-gzip"";s:4:"link";s:66:"<https://parentsblog.aris.edu.gh/wp-json/>; rel=https://api.w.org/";s:4:"vary";s:15:"Accept-Encoding";s:16:"content-encoding";s:4:"gzip";s:14:"content-length";s:4:"2931";s:12:"content-type";s:34:"application/rss+xml; charset=UTF-8";}s:5:"build";s:14:"20121030175403";}